sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # this will be used to set unique image image in deploy.sh
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #this will disable if glcoud to promt user to enter anything
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d 
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json #create servie account and download credentails as json
    # docker run -it -v $(pwd):/app sh 
    #use travis cli to encrypt travis encrypt-file filename. 
  - gcloud config set project multi-container-cluster #Poject ID in Goolge it will be defferent as project name
  - gcloud config set compute/zone asia-south1-a # Zone where we create 
  - gcloud container clusters get-credentials my-cluster # name of the cluster
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rvettom/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true rvettom/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
